name: Deploy to Okteto

on:
  push:
    branches:
      - master

jobs:
  deploy-to-okteto:
    name: Deploy to Okteto
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - uses: okteto/login@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - uses: okteto/create-namespace@latest
        with:
          namespace: vaadin-quarkus-${{ github.actor }}

      - uses: okteto/deploy-stack@latest
        with:
          build: "true"
